### ISSUE TITLE
Move tabs between groups

### ISSUE THREAD

**Issue by skyschub** [denschub/firefox-tabgroups#1]

**Comment by saithis** [comment]
It would be awesome, if you could drag and drop the tabs between groups.
The same could be used to reorder the tabs in a group.

**Comment by afranke** [comment]
That seems very important since one use for tab groups is to move tabs out of current group once you realize you have too many.

**Comment by afranke** [comment]
Excellent, works great. Thanks a lot!

**Comment by hrlmartins** [comment]
Sorry to reply to this. Does it still work? Tried to drag some tab to the icon on the toolbar and it didn't show the popup with the multiple groups. Not really sure if this is the use case :P

Firefox 55.0.3 on Mac OS X 10.13

**Comment by afranke** [comment]
Firefox 55.0.3 on Fedora 26, still works.

**Comment by hrlmartins** [comment]
Just between these comments ff updated itself to 56 :P. But still the same problem. But just wanted to know: is it expected for you to drag the tab to the tab group icon on the toolbar?

FYI: I'm using the tree style tab addon, might be messing with this
FYI2: Nope, just tried to disable it.

**Comment by afranke** [comment]
This has to be done from the group overview.

**Comment by hrlmartins** [comment]
... nevermind, I get it now xD
