### ISSUE TITLE
Please add your add-on to official "Learn more" page

### ISSUE THREAD

**Issue by Noitidart** [denschub/firefox-tabgroups#19]
In Firefox 44 we now get a warning saying tabgroups will be discontinued. Clicking the "Learn More" launches this site:

https://support.mozilla.org/en-US/kb/tab-groups-removal

There add-ons like Tab Groups, OneTab, etc are listed, yours is not, please get it on there :)

**Comment by skyschub** [comment]
Changes are waiting for review.

**Comment by Noitidart** [comment]
Thanks!
