### ISSUE TITLE
Pretty buggy

### ISSUE THREAD

**Issue by Noitidart** [denschub/firefox-tabgroups#20]
I've been trying to use this.

I can't focus the group name when i create new one to rename it I have to tab through till i get to that field.

When I click any group it always makes a new tab.

And when I switch back to my old tab it seems to put that tab back in my old group.

:(

**Comment by skyschub** [comment]
Firefox version? Does your Firefox build still contain Panorama or do you use a built which got Panorama already removed? Also, do you have Quicksavers Panorama porting extension installed?

**Comment by Noitidart** [comment]
Firefox 44 beta yes with old panorama! thanks!

**Comment by skyschub** [comment]
thanks! (closing as discussed on irc)
