### ISSUE TITLE
Switching between groups/tabs fails if currently active tab is pinned

### ISSUE THREAD

**Issue by chrominance** [denschub/firefox-tabgroups#27]
Normally, switching between tabs is a matter of opening the menu and selecting a group (to open the last opened/first tab in that group) or expanding a group and selecting a tab inside it (to open a specific tab). This behavior works fine when you're in a tab that's already in a group.

If you're currently in a pinned tab, however, neither method works for switching tabs. The tab menu opens and you can expand/collapse groups, but selecting either a group or a tab fails silently (as if you never clicked the item at all). You have to first switch manually to an unpinned tab, and then the menu again allows you to click groups or tabs to switch to them.

**Comment by skyschub** [comment]
Eh, right. Sorry for that. I published a hotfix which is already on AMO. If your addon is not already updated to 0.2.1, click "Check for updates" in the Addon manager and it will update.

Thanks for the report!

**Comment by chrominance** [comment]
Thanks for the fix! Works like a charm.
