### ISSUE TITLE
Panel is displaced when the button is not in the menubar or the dropdown menu

### ISSUE THREAD

**Issue by skyschub** [denschub/firefox-tabgroups#3]

**Comment by groovecoder** [comment]
If you provide more detailed steps to reproduce, I might try to fix this ...

**Comment by skyschub** [comment]
Enable the shortcut in the Add-ons preferences and use the Australis customize view to move the button into the "Additional Tools and Features" area.

Then, use the shortcut to open the panel. If your window is maxmized, the panel will be outside the screen. If it's in a smaller window, the panel will be somewhere above/below the window.

**Comment by skyschub** [comment]
I'll close this issue, since it will get obsolete by the upcoming WebExtension release of this addon.
