### ISSUE TITLE
Switch to an opened tab found in awesome bar doesn't activate the group it belongs to

### ISSUE THREAD

**Issue by chyiz** [denschub/firefox-tabgroups#37]
## Steps to reproduce:
1. Open some tabs
2. Create new group and switch to it.
3. Search for one of the open tabs in awesome bar.
4. Select the search result
## Actual Results:

Only the selected tab is displayed. The previous group is not activated.
## Expected Results:

Activate the previous group and switch to the selected tab.

**Comment by chyiz** [comment]
Probably related to #11

**Comment by skyschub** [comment]
I'll close this issue, since it will get obsolete by the upcoming WebExtension release of this addon.
