### ISSUE TITLE
Dragging into/out of the current tab group does not update tabs

### ISSUE THREAD

**Issue by sabberworm** [denschub/firefox-tabgroups#42]
When I drag tabs from other groups into the currently selected group or from the current group into another one, the tab headings in the browser window does not update. It’s only updated when switching groups and back again.

Note: dragging the active tab works (presumably because that switches groups), the problem only exists with other tabs.

**Comment by chiraag-nataraj** [comment]
Do we know why this is happening yet?

**Comment by skyschub** [comment]
I'll close this issue, since it will get obsolete by the upcoming WebExtension release of this addon.
