### ISSUE TITLE
Menu does not scroll when dragging tabs

### ISSUE THREAD

**Issue by Celti** [denschub/firefox-tabgroups#43]
Running Fx 46.0.1 on Arch Linux current.

Just installed this (so very very glad it exists, as this was basically what I already had set up before Panorama was removed) — of course I had one gigantic tab group of about  a hundred and twenty tabs. 

Went to start splitting it into groups, discovered that the menu wouldn't scroll down to the new group I'd created while dragging, meaning I had to work from the bottom in a rather inconvenient fashion.

I don't think this is intentional — but if it is, please consider reopening #29 and adding a context menu — in fact, please consider adding a context menu anyway! The task process of “Open menu -> Find tab -> Right-click -> Select new group” is much quicker and less error-prone than drag-and-drop, especially with large tab volumes.

**Comment by skyschub** [comment]
I'll close this issue, since it will get obsolete by the upcoming WebExtension release of this addon.
