### ISSUE TITLE
Closing a group closes pinned tabs

### ISSUE THREAD

**Issue by SuperTux88** [denschub/firefox-tabgroups#49]
## Steps to reproduce:
1. Create new group and switch to it.
2. Open some tabs and pin one of them.
3. Switch back to the old group.
4. Close the new group from step 1.
## Expected Results:

The pinned tab stays pinned.
## Actual Results:

The pinned tab is gone now 😿

**Comment by skyschub** [comment]
I'll close this issue, since it will get obsolete by the upcoming WebExtension release of this addon.
