### ISSUE TITLE
Title's Text Desapearing

### ISSUE THREAD

**Issue by federicorp** [denschub/firefox-tabgroups#54]
It seems to be a problem with the letters when I open the tool.

This is a gif explaining what's happening:
http://federicorp.com/bug_tabs.gif (or the one attached)

It started about 5 days ago.
I am currently using Firefox 51.0a2.
![bug_tabs](https://cloud.githubusercontent.com/assets/2580887/20390974/ec07708e-acaf-11e6-924f-765a312e1209.gif)

**Comment by skyschub** [comment]
Fancy! Which version of windows are you using?

**Comment by federicorp** [comment]
Windows 7 Professional SP1.

**Comment by federicorp** [comment]
Now I removed the add-on and installed all over again and the problem remains (and also the tabs group I had before).

I can't tell the Steps to reproduce because it just happened.

And it's funny how in another computer with Windows 10 and same version of firefox works like a charm.

**Comment by federicorp** [comment]
I don't know what happened but today's working again! Thanks!

**Comment by skyschub** [comment]
Cool.
