### ISSUE TITLE
Closing last tab in group shows tab from other group

### ISSUE THREAD

**Issue by matthijskooijman** [denschub/firefox-tabgroups#57]
When I close the last tab in a group, instead of opening a new "blank" tab, a tab from another group is shown. I'm not so sure how this other tab is chosen, in one case I saw the first tab from the next group, in another case it was the last tab from 4 groups above.

The tab that is shown is *not* moved into the current group, since switching to another group and back makes it disappear again.

I'm using Firefox 45.4.0 and Simplified Tab Groups 0.5.1.

**Comment by skyschub** [comment]
This will be fixed whenever I release the version currently in development, which hopefully won't be that far away. This was fixed by #51, so I'll close this.

Still, thanks for the report! :)
