### ISSUE TITLE
Close last tab in group shows last used tab from last group

### ISSUE THREAD

**Issue by SuperTux88** [denschub/firefox-tabgroups#6]
### Steps to reproduce:
1. Open some tabs
2. Create new group and switch to it.
3. Close the "New Tab" tab.
### Actual Results:

The last used tab from the first group shows up, but the second tabgroup is still selected.
### Expected Results:

The empty tabgroup should be removed and the whole last tabgroup should become active.

**Comment by skyschub** [comment]
Fixed by #51.
