### ISSUE TITLE
e10s / electrolysis / Web extension compatibilty

### ISSUE THREAD

**Issue by xfr-dev** [denschub/firefox-tabgroups#62]
Hi,

I've just migrated from using [TabGroupsPanorama](https://addons.mozilla.org/fr/firefox/addon/tab-groups-panorama/) extension to Simplified Tab Groups because the first one will stop working when Firefox will support only WebExtension around november 2017.
Could-you tell me if this extension will be compatible and thus converted as WebExtension till then?
Thanks, regards,
xfr

**Comment by skyschub** [comment]
https://github.com/denschub/firefox-tabgroups/issues/60

>> will this plugin survive
> 
> yes.
