### ISSUE TITLE
Scope of 'Simplified'

### ISSUE THREAD

**Issue by grahamperrin** [denschub/firefox-tabgroups#67]
### Example 1 

A June 2017 screenshot of one of my windows:  

![2017-06-19 example](https://user-images.githubusercontent.com/192271/27319954-e93b0bb0-558b-11e7-863f-791738203107.png)

– that's the _Manage my groups_ interface of [Tab Groups](https://addons.mozilla.org/firefox/addon/tab-groups-panorama/) by Luís Miguel (Quicksaver), which was [discontinued](http://web.archive.org/web/20170128221346/http://fasezero.com/lastnotice.html) as a result of Mozilla's directions towards WebExtensions.  

### Example 2

Today, [Tab Tally](https://addons.mozilla.org/firefox/addon/tab-tally/) shows four hundred and thirty-seven tabs (thirty-four loaded). 

### Generally

I keep the caboodle well-organised but there _is_ a lot going on, typically: 

- **hundreds of tabs**
- **ten windows** (_never_ too many; any more than twelve Firefox windows, interspersed with other applications, feels excessive)
- **between four and ten groups per window** (_rarely_ more than twenty per window)

– a relatively complex use case. 

### Ease of use

I typically use the contextual menu features of Tab Groups (not the management interface pictured above) to move from one group to another. So I like the idea of [Add tab context menu to move a tab to another group · Issue #29 · denschub/firefox-tabgroups](https://github.com/denschub/firefox-tabgroups/issues/29), I wonder whether it might be reopened …

… or would you describe use cases such as mine as **out of scope** for Simplified Tab Groups? 

----

Big love for: 

- [Move groups between windows · Issue #5 · denschub/firefox-tabgroups](https://github.com/denschub/firefox-tabgroups/issues/5)

**Comment by skyschub** [comment]
If you have any actual issues, feature requests or whatever, feel free to open them, but I don't see anything actionable here.

**Comment by grahamperrin** [comment]
OK, there's the plea to re-open #29.
