### ISSUE TITLE
Tabs mixed up between groups on relaunch

### ISSUE THREAD

**Issue by ryansigg** [denschub/firefox-tabgroups#68]
When closing and re-opening Firefox, most tabs are moved into one group and must be manually moved back into their previous groups. Tab groups remain intact, and there are usually one or two tabs left in each group, sometimes more. No discernable pattern.

OS: MacOS Sierra 10.12.6
Browser version: 54.0.1 

Extensions used:
Lastpass
Web Developer Toolbar
OneTab
Tab Suspender
uBlock Origin

**Comment by grahamperrin** [comment]
Considering [Issues · rNeomy/tab-suspender](https://github.com/rNeomy/tab-suspender/issues)

Please tell whether the issue here – the mix-up affecting _Simplified Tab Groups_ – is reproducible **without** _Tab Suspender_. 

Thanks

**Comment by ryansigg** [comment]
Deactivating Tab Suspender seems to take care of this issue.
Another issue that I thought was related, where tab groups become unresponsive when clicked, seems to persist. This only happens intermittently, so I'll try to keep an eye our for patterns to this one.
Thanks.
