### ISSUE TITLE
Compaability with Sessiom manager

### ISSUE THREAD

**Issue by Dugahot** [denschub/firefox-tabgroups#74]
1. It is impossible save tabs of a current group as a session. Session manager can see only one group;
2. It is impossible to restore a session to a chosen group but only to specific that Session manager can see;
3. The issue as a response to recent crash and no backup.
Thanks

**Comment by grahamperrin** [comment]
To put this issue partly in the context of WebExtensions APIs: 

- Mozilla bug [1407486 - no way to configure Firefox to automatically restore sessions](https://bugzilla.mozilla.org/show_bug.cgi?id=1407486) (2017-10-10)

There two days ago: 

> … added to the agenda for the October 31 WebExtensions APIs triage meeting. …

@Dugahot would you like to slightly correct your title for this issue? 

_Compatibility with Session Manager_

– thank you.

**Comment by skyschub** [comment]
I'm closing this, since it has absolutely no relevance to the addon. If you enable session restore, groups will be restored. If you disable session restore, tabs won't be there, so won't be groups.
