### ISSUE TITLE
Post-update Quantum - Restore hidden tabs

### ISSUE THREAD

**Issue by leup** [denschub/firefox-tabgroups#77]
Hello people !

Firefox has updated to v57 and so the add-onis not compatible anymore.
My issue is that now I have only the tabs that were not hidden before the update/restart of FF that show up.
Would there be anyway to un-hide all the tabs ? Or are they lost ?

Thanks for you help

**Comment by SuperTux88** [comment]
See https://github.com/denschub/firefox-tabgroups/issues/60#issuecomment-322005792 for how to restore hidden tabs.

**Comment by smonff** [comment]
See also this https://github.com/Morikko/sync-tab-groups

**Comment by leup** [comment]
I already tried the #60 comment (I should have told that) but I get an error "gBrowser" is undefined. I am probably doing something wrong. Any help appreciated.

**Comment by skyschub** [comment]
Are you inside the browser console, not the web console?

**Comment by leup** [comment]
Ok I did not know that there is a so called browser console, now I know.
So:
* Open the dev console
* Go to settings
* Activate the chrome debugging
* **Ctrl+Maj+J to open the browser console**

Just so you know, I tried the other plugin linked by @smonff and it bringed back my tabs instantly.
So there is two ways to get them back and I am really happy. :)

Thanks for your help !
