### ISSUE TITLE
will updating delete or combine the groups? backups?

### ISSUE THREAD

**Issue by zane49er2** [denschub/firefox-tabgroups#78]
This morning (6:00) I updated to quantum and it looked like I was in my selected group. I downgraded, the plug-in was still broken, and it looked like only group one was left. I want to keep all of my tabs, so what do I need to do? Can I make a backup? Would there be any automatic ones left?

**Comment by skyschub** [comment]
Read this https://github.com/denschub/firefox-tabgroups/issues/60#issuecomment-322005792 to restore all your tabs when upgrading.
