### ISSUE TITLE
Port to WebExtension #60

### ISSUE THREAD

**Issue by brunoais** [denschub/firefox-tabgroups#81]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423725 is now on Nightly.
Are you able to resume your work on this extension? If not, what's missing?

**Comment by skyschub** [comment]
I said in https://github.com/denschub/firefox-tabgroups/issues/60#issuecomment-343347026 that I will update the issue when I have something to update. I also said I will port the extension as soon as all required APIs are implemented and I had the time to actually port it. And all these statements are still valid.

I am not a wizard.
