### ISSUE TITLE
Add confirmation when closing a group

### ISSUE THREAD

**Issue by SuperTux88** [denschub/firefox-tabgroups#9]

**Comment by Swatinem** [comment]
:+1: 
Or alternative provide an undo action.
I just accidently closed a whole group and actually had to mess around with the sessionrestore data to get it back. That was a really terrifying experience tbh :-D

**Comment by hheimbuerger** [comment]
I'm running 0.3.0, but was this feature actually released in that? Any documentation on how to invoke it? Or is the milestone incorrect?

**Comment by skyschub** [comment]
This issue is still open, which means it's not implemented yet.

**Comment by hheimbuerger** [comment]
@denschub Yes, but it's also flagged as "Milestone 0.3.0", which is [already released](https://github.com/denschub/firefox-tabgroups/releases/tag/v0.3.0). So one of these two data points has to be incorrect. :)

**Comment by skyschub** [comment]
Better now?

**Comment by hheimbuerger** [comment]
@denschub Cheers! :)

**Comment by skyschub** [comment]
Technically solved by #34.

**Comment by aaronraimist** [comment]
How long until you expect 0.6.0 will be released with this feature?

**Comment by skyschub** [comment]
@aaronraimist meh, sorry. I'm busy with work. Will try to ship the release next week, I promise!

**Comment by whiskytroll** [comment]
I'm sorry if I'm being dense, but is this feature about restoring groups or adding a confirmation when closing groups or both? Additionally it would be nice to know when it's being rolled out?

**Comment by skyschub** [comment]
> but is this feature about restoring groups or adding a confirmation when closing groups or both?

You can restore closed groups within a defined period of time.

> Additionally it would be nice to know when it's being rolled out?

#60.

**Comment by whiskytroll** [comment]
Thanks!
